<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fundamentos de JavaScript</title>
  </head>
  <body>
    <h1>Fundamentos de JavaScript</h1>

    <script>


      try{
        console.log("En el try se agrega el código a evaluar");
        noexiste;
        console.log("Un segundo mensaje en el try");
      }catch(error){
        console.log("Catch captura cualquier error surgido o lanzado en el try");
        console.log(error);
      }finally{
        console.log("El bloque finally se ejecutará siempre al final de un bloque try-catch")
      }

      //Personalizar mensajes try catch

      try{
        let numero = "y";
        
        if(isNaN(numero)){
          throw new Error("El caractér introducido no es un número");
        }

        console.log(numero * numero);
      }catch(error){
        console.log(`Se produjo el siguiente error: ${error}`)
      }finally{
        
      }



    </script>
  </body>
</html>
